package test; 

import http.org.drools.conyard.owl.*;

global java.util.List ans;
                
declare trait Manager
end

declare trait IronInstallation
end



rule "Check type"
when
    $p : Painting()
then
    ans.add("type");
end


rule "Check nested properties and types"
when
    $p : Painting( $stair : requiresStairAsPainting )
    $s : Stair( stairLengthIntegerAsStair == 10 ) from $stair
then
    ans.add("nestedProperties");
end
