/*
 * Copyright 2011 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.drools.chance.test;

import org.drools.chance.builder.Imperfect;

import org.drools.chance.common.fact.Weight;
import org.drools.chance.common.fact.Price;

import org.drools.chance.degree.DegreeType;


declare Cheese
    name    : String   @key
end


declare LegacyBean
    @Traitable
    name    : String
    weight  : Double
end




declare BeanImp
	name    : String    = "john/0.3, philip/0.7"
	                @Imperfect( kind=ImpKind.PROBABILITY, type=ImpType.DISCRETE, degree=DegreeType.SIMPLE )

	flag    : Boolean    = "true/0.75, false/0.25"
	                @Imperfect( kind=ImpKind.PROBABILITY, type=ImpType.DISCRETE, degree=DegreeType.SIMPLE )

	age     : Integer   = "18/0.02, 19/0.01, 20/0.04"
	                @Imperfect( kind=ImpKind.PROBABILITY, type=ImpType.DIRICHLET, degree=DegreeType.SIMPLE )

    body    : Weight    = "SLIM/0.6, FAT/0.4"
                    @Imperfect( kind=ImpKind.FUZZINESS, type=ImpType.LINGUISTIC, degree=DegreeType.SIMPLE, support="weight" )

    weight  : Double    = 65.0


    price   : Price
                    @Imperfect( kind=ImpKind.FUZZINESS, type=ImpType.LINGUISTIC, degree=DegreeType.SIMPLE, support="bucks" )

    bucks   : Integer


    likes   : Cheese    = "cheddar/0.6"
                    @Imperfect( kind=ImpKind.PROBABILITY, type=ImpType.BASIC, degree=DegreeType.SIMPLE )

end



declare ImpTrait
    @format( trait )
    @typesafe( false )

	name    : String
	                @Imperfect( kind=ImpKind.PROBABILITY, type=ImpType.DISCRETE, degree=DegreeType.SIMPLE )

	flag    : Boolean
	                @Imperfect( kind=ImpKind.PROBABILITY, type=ImpType.DISCRETE, degree=DegreeType.SIMPLE )

	age     : Integer
	                @Imperfect( kind=ImpKind.PROBABILITY, type=ImpType.DIRICHLET, degree=DegreeType.SIMPLE )

    body    : Weight
                    @Imperfect( kind=ImpKind.FUZZINESS, type=ImpType.LINGUISTIC, degree=DegreeType.SIMPLE, support="weight" )

    weight  : Double


    price   : Price
                    @Imperfect( kind=ImpKind.FUZZINESS, type=ImpType.LINGUISTIC, degree=DegreeType.SIMPLE, support="bucks" )

    bucks   : Integer


    likes   : Cheese
                    @Imperfect( kind=ImpKind.PROBABILITY, type=ImpType.BASIC, degree=DegreeType.SIMPLE )
end



rule "Init I"
 when
 then
     LegacyBean b = new LegacyBean( "joe", 65.0 );
     ImpTrait imp = don( b, ImpTrait.class );
end



rule "Init II"
when

then
    insert( new BeanImp( ) );
end


rule "Bind"
when

then
end