
package org.drools.chance.test;

import org.drools.chance.common.Bean;
import org.drools.chance.builder.ChanceFactory;
import org.drools.chance.builder.ImperfectRegistry;
import org.drools.chance.builder.Imperfect;

import org.drools.chance.common.fact.Weight;
import org.drools.chance.common.fact.Price;



declare Cheese
    name    : String   @key
end


declare LegacyBean
    @Traitable
    name    : String
    weight  : Double
end




declare BeanImp
	name    : String    = "john/0.3, philip/0.7"
	                @Imperfect( kind="probability", type="discrete", degree="simple" )

	flag    : Boolean    = "true/0.75, false/0.25"
	                @Imperfect( kind="probability", type="discrete", degree="simple" )

	age     : Integer   = "18/0.02, 19/0.01, 20/0.04"
	                @Imperfect( kind="probability", type="dirichlet", degree="simple" )

    body    : Weight    = "SLIM/0.6, FAT/0.4"
                    @Imperfect( kind="fuzzy", type="linguistic", degree="simple", support="weight" )

    weight  : Double

    likes   : Cheese    = "cheddar/0.6"
                    @Imperfect( kind="probability", type="basic", degree="simple" )

end



declare ImpTrait
    @format( trait )
    @typesafe( false )

	name    : String
	                @Imperfect( kind="probability", type="discrete", degree="simple" )

	flag    : Boolean
	                @Imperfect( kind="probability", type="discrete", degree="simple" )

	age     : Integer
	                @Imperfect( kind="probability", type="dirichlet", degree="simple" )

    body    : Weight
                    @Imperfect( kind="fuzzy", type="linguistic", degree="simple", support="weight" )

    weight  : Double


    price   : Price
                    @Imperfect( kind="fuzzy", type="linguistic", degree="simple", support="bucks" )

    bucks   : Integer


    likes   : Cheese
                    @Imperfect( kind="probability", type="basic", degree="simple" )
end



rule "Init I"
 when
 then
     LegacyBean b = new LegacyBean( "joe", 65.0 );
     ImpTrait imp = don( b, ImpTrait.class );
end



rule "Init II"
when

then
    insert( new BeanImp( ) );
end


