package org.drools.chance.trait.drl

import org.drools.chance.common.Bean;
import org.drools.chance.builder.ChanceFactory;
import org.drools.chance.builder.ImperfectRegistry;
import org.drools.chance.builder.Imperfect;
import org.drools.chance.distribution.IDistribution;
import org.drools.chance.common.IImperfectField;


import org.drools.chance.common.Weight;
import org.drools.chance.common.Price;


global java.util.List list;

declare LegacyBean
    @Traitable
    name    : String
    weight  : Double
end

declare Cheese
    name    : String   @key
end




declare ImpBean
    @format( trait )
    @typesafe( false )

	name    : String
	                @Imperfect( kind="probability", type="discrete", degree="simple" )

	flag    : Boolean
	                @Imperfect( kind="probability", type="discrete", degree="simple" )

	age     : Integer
	                @Imperfect( kind="probability", type="dirichlet", degree="simple" )

    body    : Weight
                    @Imperfect( kind="fuzzy", type="linguistic", degree="simple", support="weight" )

    weight  : Double


    price   : Price
                    @Imperfect( kind="fuzzy", type="linguistic", degree="simple", support="bucks" )

    bucks   : Integer


    likes   : Cheese
                    @Imperfect( kind="probability", type="basic", degree="simple" )
end



rule "Init"
 when
 then
     LegacyBean b = new LegacyBean( "joe", 65.0 );
     ImpBean imp = don( b, ImpBean.class );
end






/*


rule "Wrap II"
when
    $p : Imperson( $name : name, $dist : nameDistr, $val : nameValue )
then
    System.out.println( " >> " + $p );

    System.err.println( $name );
    System.err.println( $dist );
    System.err.println( $val );

end


rule "Init"
when
then
    LegacyBean b = new LegacyBean( "joe", 65.0 );
    ImpBean imp = don( b, ImpBean.class );

        System.out.println(" *** >>>>>> " + imp );



        System.out.println(" getName   >>>>>> " + imp.getName( ) );

            System.out.println(" \t\t Initial Imp field (name) : " + imp.getName( ) );
            System.out.println(" \t\t Initial Imp distr (name) : " + imp.getNameDistr( ) );
            System.out.println(" \t\t Initial Imp alive (name) : " + imp.getNameValue( ) );

        IDistribution nameDist = imp.getName().getStrategies().parse("john/0.7,adam/0.3");
        imp.setNameDistr( nameDist );

            System.out.println(" \t\t After setting new distr (name) : " + imp.getName( ) );
            System.out.println(" \t\t After setting new distr (inner name) : " + b.getName( ) );

        imp.setName( imp.getName() );
            System.out.println(" \t\t After auto-setting impe field (name) : " + imp.getName( ) );
            System.out.println(" \t\t After auto-setting impe field (name) : " + b.getName( ) );

        imp.updateNameDistr( nameDist );
            System.out.println(" \t\t After self-update distr (name) : " + imp.getName( ) );

        imp.updateNameValue( "john" );
            System.out.println(" \t\t After updating with degenerated distro (name) : " + imp.getName( ) );
        imp.setNameValue( "david" );
            System.out.println(" \t\t After setting hard value (name) : " + imp.getName( ) );
//            System.out.println(" \t\t on Core : " + imp.getNameCore( ) );




        System.out.println(" getFlag   >>>>>> " + imp.getFlag( ) );

            System.out.println(" \t\t Initial Imp field (flag) : " + imp.getFlag( ) );
            System.out.println(" \t\t Initial Imp distr (flag) : " + imp.getFlagDistr( ) );
            System.out.println(" \t\t Initial Imp alive (flag) : " + imp.getFlagValue( ) );

        IDistribution flagDist = imp.getFlag().getStrategies().parse("true/0.6,false/0.4");
        imp.setFlagDistr( flagDist );

            System.out.println(" \t\t After setting new distr (flag) : " + imp.getFlag( ) );
            System.out.println(" \t\t After setting new distr (inner flag) : " + imp.getFields( ).get( "flag" ) );

        imp.setFlag( imp.getFlag() );
            System.out.println(" \t\t After auto-setting impe field (flag) : " + imp.getFlag( ) );
            System.out.println(" \t\t After auto-setting impe field (flag) : " + imp.getFields( ).get( "flag" ) );

        imp.updateFlagDistr( flagDist );
            System.out.println(" \t\t After self-update distr (flag) : " + imp.getFlag( ) );

        imp.updateFlagValue( true );
            System.out.println(" \t\t After updating with degenerated distro (flag) : " + imp.getFlag( ) );
        imp.setFlagValue( false );
            System.out.println(" \t\t After setting hard value (flag) : " + imp.getFlag( ) );
//            System.out.println(" \t\t on Core : " + imp.getFlagCore( ) );



        System.out.println(" getLikes   >>>>>> " + imp.getLikes( ) );

            System.out.println(" \t\t Initial Imp field (likes) : " + imp.getLikes( ) );
            System.out.println(" \t\t Initial Imp distr (likes) : " + imp.getLikesDistr( ) );
            System.out.println(" \t\t Initial Imp alive (likes) : " + imp.getLikesValue( ) );

        IDistribution likesDist = imp.getLikes().getStrategies().parse("stilton/0.7");
        imp.setLikesDistr( likesDist );

            System.out.println(" \t\t After setting new distr (likes) : " + imp.getLikes( ) );
            System.out.println(" \t\t After setting new distr (inner likes) : " + imp.getFields( ).get( "likes" ) );

        imp.setLikes( imp.getLikes() );
            System.out.println(" \t\t After auto-setting impe field (likes) : " + imp.getLikes( ) );
            System.out.println(" \t\t After auto-setting impe field (likes) : " + imp.getFields( ).get( "likes" ) );

        imp.updateLikesDistr( likesDist );
            System.out.println(" \t\t After self-update distr (likes) : " + imp.getLikes( ) );

        imp.updateLikesValue( new Cheese("stilton") );
            System.out.println(" \t\t After updating with degenerated distro (likes) : " + imp.getLikes( ) );
        imp.setLikesValue( new Cheese("mozzarella") );
            System.out.println(" \t\t After setting hard value (likes) : " + imp.getLikes( ) );
//            System.out.println(" \t\t on Core : " + imp.getLikesCore( ) );
        



        System.out.println(" getAge   >>>>>> " + imp.getAge( ) );

            System.out.println(" \t\t Initial Imp field (age) : " + imp.getAge( ) );
            System.out.println(" \t\t Initial Imp distr (age) : " + imp.getAgeDistr( ) );
            System.out.println(" \t\t Initial Imp alive (age) : " + imp.getAgeValue( ) );

        IDistribution ageDist = imp.getAge().getStrategies().parse("18/4,19/8");
        imp.setAgeDistr( ageDist );

            System.out.println(" \t\t After setting new distr (age) : " + imp.getAge( ) );
            System.out.println(" \t\t After setting new distr (inner age) : " + imp.getFields( ).get( "age" ) );

        imp.setAge( imp.getAge() );
            System.out.println(" \t\t After auto-setting impe field (age) : " + imp.getAge( ) );
            System.out.println(" \t\t After auto-setting impe field (age) : " + imp.getFields( ).get( "age" ) );

        imp.updateAgeDistr( ageDist );
            System.out.println(" \t\t After self-update distr (age) : " + imp.getAge( ) );

        imp.updateAgeValue( 19 );
            System.out.println(" \t\t After updating with degenerated distro (age) : " + imp.getAge( ) );
        imp.setAgeValue( 19 );
            System.out.println(" \t\t After setting hard value (age) : " + imp.getAge( ) );
//            System.out.println(" \t\t on Core : " + imp.getAgeCore( ) );
        





        System.out.println(" getPrice   >>>>>> " + imp.getPrice( ) );

            System.out.println(" \t\t Initial Imp field (price) : " + imp.getPrice( ) );
            System.out.println(" \t\t Initial Imp distr (price) : " + imp.getPriceDistr( ) );
            System.out.println(" \t\t Initial Imp alive (price) : " + imp.getPriceValue( ) );



        IDistribution priceDist = imp.getPrice().getStrategies().parse("INEXPENSIVE/0.4,CHEAP/0.6");
        IDistribution priceDist2 = imp.getPrice().getStrategies().parse("REASONABLE/0.7,EXPENSIVE/0.3");
        imp.setPriceDistr( priceDist );

            System.out.println(" \t\t After setting new distr (price) : " + imp.getPrice( ) );
            System.out.println(" \t\t After setting new distr (inner price) : " + imp.getFields( ).get( "price" ) );
            System.out.println(" \t\t *** Support field value (bucks) : " + imp.getBucks( ) );

        imp.setPrice( imp.getPrice() );
            System.out.println(" \t\t After auto-setting impe field (price) : " + imp.getPrice( ) );
            System.out.println(" \t\t After auto-setting impe field (price) : " + imp.getFields( ).get( "price" ) );
            System.out.println(" \t\t *** Support field value (bucks) : " + imp.getBucks( ) );

        imp.updatePriceDistr( priceDist2 );
            System.out.println(" \t\t After update distr2 (price) : " + imp.getPrice( ) );
            System.out.println(" \t\t *** Support field value (bucks) : " + imp.getBucks( ) );

        imp.updatePriceValue( Price.REASONABLE );
            System.out.println(" \t\t After updating with degenerated distro (price) : " + imp.getPrice( ) );
            System.out.println(" \t\t *** Support field value (bucks) : " + imp.getBucks( ) );
        imp.setPriceValue( Price.BLOODY_HELL );
            System.out.println(" \t\t After setting hard value (price) : " + imp.getPrice( ) );
            System.out.println(" \t\t *** Support field value (bucks) : " + imp.getBucks( ) );
//            System.out.println(" \t\t on Core : " + imp.getPriceCore( ) );

        imp.setBucks(50);
            System.out.println(" \t\t After setting crisp value (bucks) : " + imp.getPrice( ) );
            System.out.println(" \t\t *** Support field value (bucks) : " + imp.getBucks( ) );




//        System.out.println(" getBody   >>>>>> " + imp.getBody( ) );
//
//            System.out.println(" \t\t Initial Imp field (body) : " + imp.getBody( ) );
//            System.out.println(" \t\t Initial Imp distr (body) : " + imp.getBodyDistr( ) );
//            System.out.println(" \t\t Initial Imp alive (body) : " + imp.getBodyValue( ) );
//            System.out.println(" \t\t *** Support field value (weight) : " + imp.getWeight( ) );
//
//
//
//        IDistribution bodyDist = imp.getBody().getStrategies().parse("SLIM/0.7");
//        IDistribution bodyDist2 = imp.getBody().getStrategies().parse("SLIM/0.8,FAT/0.2");
//        imp.setBodyDistr( bodyDist );
//
//            System.out.println(" \t\t After setting new distr (body) : " + imp.getBody( ) );
//            System.out.println(" \t\t After setting new distr (inner body) : " + imp.getFields( ).get( "body" ) );
//            System.out.println(" \t\t *** Support field value (weight) : " + imp.getWeight( ) );
//
//        imp.setBody( imp.getBody() );
//            System.out.println(" \t\t After auto-setting impe field (body) : " + imp.getBody( ) );
//            System.out.println(" \t\t After auto-setting impe field (body) : " + imp.getFields( ).get( "body" ) );
//            System.out.println(" \t\t *** Support field value (weight) : " + imp.getWeight( ) );
//
//        imp.updateBodyDistr( bodyDist2 );
//            System.out.println(" \t\t After update distr2 (body) : " + imp.getBody( ) );
//            System.out.println(" \t\t *** Support field value (weight) : " + imp.getWeight( ) );
//
//        imp.updateBodyValue( Weight.SLIM );
//            System.out.println(" \t\t After updating with degenerated distro (body) : " + imp.getBody( ) );
//            System.out.println(" \t\t *** Support field value (weight) : " + imp.getWeight( ) );
//        imp.setBodyValue( Weight.FAT );
//            System.out.println(" \t\t After setting hard value (body) : " + imp.getBody( ) );
//            System.out.println(" \t\t *** Support field value (weight) : " + imp.getWeight( ) );
//
//
//        imp.setWeight(55.0);
//            System.out.println(" \t\t After setting crisp value (weight) : " + imp.getBody( ) );
//            System.out.println(" \t\t *** Support field value (weight) : " + imp.getWeight( ) );
//
//        imp.setWeight(25.0);
//            System.out.println(" \t\t After setting crisp value (weight) : " + imp.getBody( ) );
//            System.out.println(" \t\t *** Support field value (weight) : " + imp.getWeight( ) );
//
//        imp.setBodyDistr( bodyDist2 );
//            System.out.println(" \t\t After set distr2 (body) : " + imp.getBody( ) );
//            System.out.println(" \t\t *** Support field value (weight) : " + imp.getWeight( ) );

end
         */

