package drl;

import org.semanticweb.owlapi.model.*;
import org.semanticweb.owlapi.vocab.*;
import uk.ac.manchester.cs.owl.owlapi.*;

import org.w3._2001.xmlschema.*;
import javax.xml.namespace.QName;

import javax.xml.bind.*;
import java.util.Set;
import java.util.HashSet;

import org.test.*;
import org.test.beans.*;

global OWLOntology ontology;
global OWLOntologyManager manager;
global OWLDataFactory factory;
global String tns;




























rule "Named Simple Types"
when
    $s : SimpleType( $name : name )
then
end


/* BUGGED LHS!!!!!!!!!!!!
*/
rule "Named Simple Types Enum"
when
    SimpleType( $name : name != null, union == null,
                $facets : restriction.facets )
    $set : Set() from accumulate(
                $fax : Object(  ) from $facets,
                init( Set set = new HashSet(); ),
                action( $set.add( $fax );
                         ),
                result( $set ) )
then
end
