/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 *
 * Copyright 2011 JBoss Inc
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.drools.chance.test;

import org.drools.chance.factmodel.Imperfect;
import org.drools.chance.factmodel.LinguisticPartition;

import de.lab4inf.fuzzy.FuzzySet;
import de.lab4inf.fuzzy.polygons.FuzzyTriangle;

import org.drools.chance.degree.Degree;
import org.drools.chance.reteoo.ChanceActivation;

import java.util.Map;

global java.util.Map map;

    /*

       SLIM      FAT
  1.0    | \     / |
         |   \ /   |
         |   / \   |
  0.0    | /     \ |
       --------------->
         0         100
    */


declare enum Weight
@LinguisticPartition

	SLIM( "slim", new de.lab4inf.fuzzy.polygons.FuzzyTriangle( -0.01, 0, 100 ) ),

	FAT( "fat", new de.lab4inf.fuzzy.polygons.FuzzyTriangle( 0, 100, 100.01 ) );

    label : String

    set   : FuzzySet

end

declare Cheese
    names   : String
end

declare Imperson
	name    : String    = "john/0.3, philip/0.7"
	                @Imperfect( kind=ImpKind.PROBABILITY, type=ImpType.DISCRETE, degree=DegreeType.SIMPLE )

	flag    : Boolean    = "true/0.75, false/0.25"
	                @Imperfect( kind=ImpKind.PROBABILITY, type=ImpType.DISCRETE, degree=DegreeType.SIMPLE )

	age     : Integer   = "18/0.02, 19/0.01, 20/0.04"
	                @Imperfect( kind=ImpKind.PROBABILITY, type=ImpType.DIRICHLET, degree=DegreeType.SIMPLE )

    body    : Weight    = "SLIM/0.6, FAT/0.4"
                    @Imperfect( kind=ImpKind.FUZZINESS, type=ImpType.LINGUISTIC, degree=DegreeType.SIMPLE, support="weight" )

    weight  : Double    = 65.0


    likes   : Cheese    = "cheddar/0.6"
                    @Imperfect( kind=ImpKind.PROBABILITY, type=ImpType.BASIC, degree=DegreeType.SIMPLE )

end


rule "Init"
when
then
    insert( new Imperson( ) );
end

rule "MVL Rule + Godel And"
when
    $b : Imperson( name ~== "philip",
                   weight ~is Weight.FAT )
            @Imperfect( family=MvlFamilies.GODEL, degree=DegreeType.SIMPLE )
then
    Degree x = chance.getDegree();
    System.out.println( "X " + x );  // min( 0.7, 0.65) = 0.65
    map.put( "X", x.getValue() );
end

rule "MVL Rule + Lukas And"
when
    $b : Imperson( name ~== "philip",
                   weight ~is Weight.FAT )
            @Imperfect( family=MvlFamilies.LUKAS, degree=DegreeType.SIMPLE )
then
    Degree x = chance.getDegree();
    System.out.println( "Y " + x );  // 0.7 + 0.65 - 1 = 0.35
    map.put( "Y", x.getValue() );
end

rule "MVL Rule + Product And"
when
    $b : Imperson( name ~== "philip",
                   body ~is Weight.FAT )
            @Imperfect( family=MvlFamilies.PRODUCT, degree=DegreeType.SIMPLE )
then
    Degree x = chance.getDegree();
    System.out.println( "Z " + x );  // 0.7*0.65 = 0.455
    map.put( "Z", x.getValue() );
end
