/*
 * Copyright 2011 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.drools.informer



rule "IncludeNotes"
no-loop
when
    $n : Note( $ctx : context, $noteId : id )
    $quest : Questionnaire( id == $ctx, itemList not contains $noteId )
then
    modify ( $quest ) {
        addItem($noteId);
    }
end



rule "RemoveUnusedNotes"
no-loop
when
    $quest : Questionnaire( $itemz : itemList )
    $itemId : String() from $itemz;
    not Item( id == $itemId )
then
    modify ( $quest ) {
        removeItem($itemId);
    }
end