/*
 * Copyright 2011 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.drools.informer



query "getQuestionnaireByType" ( String $type, Questionnaire $quest )
    $quest := Questionnaire( type == $type )
end

query "getQuestionnaire" ( String $context, Questionnaire $quest )
    $quest := Questionnaire( context == $context )
end

query "getAssociation"( Object $obj, String $prop )
    $quest : DomainModelAssociation( object == $obj, property == $prop )
end

query "getAssociations"( Object $obj )
    $quest : DomainModelAssociation( object == $obj )
end


query "activeObjects"
	object : InformerObject(active == true)
end

query "activeObjectsInContext" (String context)
	object : InformerObject( active == true, context == context )
end

query "getItemId"( String $type, String $context, String $id )
    Item( $type := type, $context := context, $id := id ) @watch(*)
end

query "getItem"( String $type, String $context, Item $item ) @watch(*)
    $item := Item( $type := type, $context := context )
end

query "erroneousAnswers"
	$ea : InvalidAnswer(  )
end

query "missingAnswers"
	$ma : InvalidAnswer( type == "missing" )
end

query "invalidAnswers"
	$ia : InvalidAnswer( type == "invalid" )
end


query "answeredQuestions"
	question : Question( answered == true ) @watch(*)
end

query "answeredQuestionsInContext" (String context)
	question : Question(answered == true, context == context) @watch(*)
end
