/*
 * Copyright 2011 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.drools.informer.interaction;

import org.drools.informer.MultipleChoiceQuestion;
import org.drools.informer.MultipleChoiceQuestion.PossibleAnswer;


    query possibleStateAnswers( String $xid, List $answers )
        getItemId( "state", $xid, $qid ; )
        MultipleChoiceQuestion( $qid := id,  $ans := possibleAnswers )
        $answers := List(  ) from accumulate( PossibleAnswer( $x : value ) from $ans, collectList( $x ) )
    end

    query possibleTransitionsAnswers( String $xid, List $answers )
        getItemId( "transition", $xid, $qid ; )
        MultipleChoiceQuestion( $qid := id,  $ans := possibleAnswers )
        $answers := List(  ) from accumulate( PossibleAnswer( $x : value ) from $ans, collectList( $x ) )
    end




rule "Init Test"
when
then
    Task t = new InteractiveTask();
        t.setActor( "dsotty" );
    insert( t );
end

rule "Transit"
when
    $t : Task( $tid : taskId )
    $s : String()
then
    retract( $s );
    insert( new TaskStateTransition( $tid, $s, "dsotty", new Date() ) );
end








rule "Log Available States"
salience -1000
when
    Task( $tid : taskId, $state : state )
    TaskStateHolder( taskId == $tid, $xid : questionnaireId )
    possibleStateAnswers( $xid, $ans ; )
then
    System.out.println( "Task S [" + $state + "] >>>>>>>>>>>>>>>>> " + ", " + $ans );
end

rule "Log Available Transitions"
salience -1000
when
    Task( $tid : taskId, $state : state )
    TaskTransitionHolder( taskId == $tid, $xid : questionnaireId )
    possibleTransitionsAnswers( $xid, $ans ; )
then
    System.out.println( "Task X [" + $state + "] >>>>>>>>>>>>>>>>> " + ", " + $ans );
end



