/*
 * Copyright 2011 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.drools.informer.interaction;

import org.drools.informer.MultipleChoiceQuestion;
import org.drools.informer.MultipleChoiceQuestion.PossibleAnswer;



rule "Init Complex Test"
when
    $s : String( this == "complexTask" )
then
    retract( $s );
    Task t = new InteractiveTask();
        t.setPotentialOwners( java.util.Arrays.asList( new String[] { "dsotty", "davide" } ) );
    insert( t );
end


rule "Init Simple Test"
when
    $s : String( this == "simpleTask" )
then
    retract( $s );
    Task t = new InteractiveTask();
        t.setOwner( "davide" );
        t.setSimple( true );
        t.setPersistent( true );
    insert( t );
end









    query possibleTransitionsAnswers( String $xid, String[] $answers )
        getItemId( "transition", $xid, $qid ; )
        MultipleChoiceQuestion( $qid := id,  $answers := possibleAnswersValues )
    end




rule "Log Available Transitions"
salience -1000
when
    Task( $tid : taskId, $state : state, $owner : owner )
    TaskTransitionHolder( taskId == $tid, $xid : questionnaireId, $designatedOwner : owner )
    possibleTransitionsAnswers( $xid, $ans ; )
then
//    System.out.println( "Task X [ " + $state + " @ " + $owner + " ] >>>>>>>>>>>>>>>>> " + ", " + java.util.Arrays.asList( $ans ) );
//    System.out.println( "(Next designated owner is " + $designatedOwner + ")" );
end



