/*
 * Copyright 2011 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

 package org.drools.semantics.lang.dl ;

import org.semanticweb.owlapi.model.*;
import org.drools.semantics.builder.model.*;
import org.drools.semantics.builder.DLUtils;













/**
    Visit rule : master
*/
rule "Insert Descriptors"
salience 1000
when
	$ontology   : OWLOntology( )
	$axiom      : OWLDeclarationAxiom( $ent : entity ) from $ontology.getAxioms( AxiomType.DECLARATION )
then
    System.err.println( "Insert ...  " + $axiom );
	insertLogical( $ent );
end

// don't know why, dataproperties aren't returned as declarations...
rule "Insert Data properties"
salience 1000
when
	$ontology   : OWLOntology( )
	$axiom      : OWLProperty( ) from $ontology.getDataPropertiesInSignature()
then
    System.err.println( "Insert ...  " + $axiom );
    insertLogical( $axiom );
end





