package org.drools.beliefs.provenance;

import com.foo.MySubKlass_;
import com.foo.MySubKlass;
import org.test.MyKlass;

dialect "mvel"

declare Test
    @Traitable
    prop : java.lang.String
end

rule "Test New"
when
    not MyKlass(  )
then
    $test = new Test();

    bolster( MySubKlass_.donMySubKlass( $test ) );
end

rule "Test Find"
when
    MyKlass( )
then
    System.out.println("Found MyKlass");
end
