/*
 * Copyright 2011 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.drools.informer.presentation;

import org.drools.informer.*;
import org.drools.informer.xml.*;


declare GUIAdapter
    itemId : String                 @key
    dirty  : boolean
end


declare SurveyTicket
    sid : String                        @key      // surveyId

    uid : String                            // user Id
    guiContext : String                     // context : Inbox, Predictive, Diagnostic
    guiInteractive : boolean                // will the rule logic modify the Q?
                                            // notice : this is not a prop of the Q, but a prop of the control logic

    questionnaire : Questionnaire           // the actual Questionnaire
end





declare QuestionGUIAdapter extends GUIAdapter
    questionName : String
    preLabel : String
    required : boolean
    answerType : String
    currentAnswer : String
    validationMessage : String
    suggestedControl : String
    singleAnswer : String
    possibleAnswers : java.util.List
    action : String
    successType : String
end


declare SurveyGUIAdapter extends GUIAdapter
//    surveyId : String                   @key
    body : String
    name : String
    expiresDate : java.util.Date
    interactive : String
    language : String
    progress : int
    contextDesc : String
    surveyClass : String
    surveyQuestions : java.util.List
end



declare ChangeGUIAdapter extends GUIAdapter
//    surveyId : String                   @key
    progress : int
    newQuestions : java.util.List
    deletedQuestions : java.util.List
    updatedQuestions : java.util.List
end



declare QuestionUpdate
    questionId  : String
end

declare QuestionInvalidate extends QuestionUpdate
end

declare QuestionFinalize extends QuestionUpdate
end


query questionUpdate( QuestionUpdate $update, QuestionGUIAdapter $adapter )
    $update  := QuestionUpdate( $qid : questionId )
    $adapter := QuestionGUIAdapter( itemId == $qid )
end



rule "Fill ticket"
salience 10000
when
    $ticket : SurveyTicket( $sid : sid, questionnaire == null)
    $quest : Questionnaire( id == $sid )
then
    $ticket.setQuestionnaire($quest);
    update($ticket);
end