package org.drools.informer.presentation;



rule "Link Survey"
when
    $ticket : SurveyTicket( $id : sid, questionnaire == null )
    $quest  : Questionnaire( id == $id )
then
    $ticket.setQuestionnaire( $quest );
    update($ticket);
end


rule "Bind Survey"
no-loop
when
    $quest  : Questionnaire( $id : id )
    not SurveyTicket( sid == $id )
then
    SurveyTicket ticket = new SurveyTicket( $id );
        ticket.setQuestionnaire( $quest );
    insert( ticket );
end

rule "Clean ticket"
no-loop
when
    $t : SurveyTicket( questionnaire != null, $qid : questionnaire.id )
    not  Questionnaire( id == $qid )
then
    retract( $t );
end


rule "Clean adapters"
when
    $gui : GUIAdapter( $id : itemId )
    not    Item( id == $id )
then
    retract( $gui );
end