//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.30 at 10:54:04 AM GMT-03:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.dmg.org/PMML-4_0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.drools.pmml_4_0.descr;
