/*
 * Copyright 2011 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.drools.informer;
import org.drools.informer.Questionnaire;
import org.drools.informer.Question;

global java.util.List list;

/*
  A questionnaire of a given Type (normally passed as a parameter)
  is created if not already present.
  The trigger is the context for which the questionnaire must be created
*/
rule "Generate On Demand"
when
    $ctx : String( )
    not Questionnaire( context == $ctx, type == "TestType" )
then
    Questionnaire q = new Questionnaire("TestType");
        q.setContext($ctx);

    Question q1 = new Question("Question 1", "Please Answer Question 1");
        q1.setAnswerType(Question.QuestionType.TYPE_TEXT);
        q1.setContext($ctx);

    insert(q);
    insert(q1);
end


rule "onAnswer"
when
    Question( type == "Question 1",
              answer == "xyz",
              $ctx: context ) @watch( * )
then
    list.add($ctx);
end