package org.drools.beliefs.provenance;

import org.test.*;
import com.foo.*;
import org.drools.core.metadata.*;
import org.drools.beliefs.provenance.annotations.*;
import static org.drools.core.metadata.With.*;
import org.drools.core.metadata.Lit;
import java.util.*;

import static com.foo.MetaFactory.*;
import static org.test.MetaFactory.*;


global List list;

rule Link
when
    $t : MyTargetKlass( )
then
    insertLogical( newMyKlass( "1" ) );
end

rule Check
when
    $k : MyKlass()
then
    list.add( $k );
end
