package org.drools.beliefs.provenance;

import org.test.*;
import com.foo.*;
import org.drools.core.metadata.*;
import org.drools.beliefs.provenance.annotations.*;
import static org.drools.core.metadata.With.*;
import org.drools.core.metadata.Lit;
import java.util.*;

import static com.foo.MetaFactory.*;
import static org.test.MetaFactory.*;


global List list;

rule Link
when
then
    MyKlass mk = insertLogical( newMyKlass( "1" ) ).as( MyKlass.class );
    list.add( mk.getId() );
end

