package org.drools.chance.probability;

import org.drools.chance.factmodel.Imperfect;
import org.drools.chance.distribution.probability.gaussian.*;

import org.drools.chance.degree.Degree;

import org.drools.chance.ChanceHelper;

global java.util.Map map;



declare Imperson
@propertyReactive

    foo             : int

	age             : Double = "N(18,2)" @Imperfect( kind=ImpKind.PROBABILITY, type=ImpType.GAUSSIAN, degree=DegreeType.SIMPLE )

	weight          : Double             @Imperfect( kind=ImpKind.PROBABILITY, type=ImpType.GAUSSIAN, degree=DegreeType.SIMPLE )
end



rule "Init"
when
then
    insert( new Imperson() );
end


rule "Log"
no-loop
when
    $p : Imperson( $a : age ~> 16 && ~< 20 )
then
    System.out.println( chance.getDegree() );
    map.put( "P", $p );
    map.put( "x", chance.getDegree() );
    modify ( $p ) {
        setWeightDistr( new GaussianDistribution( 75.0, 5.0, chance.getDegree().False() ) );
    }
end

