package org.drools.beliefs.provenance;

import org.test.*;
import com.foo.*;
import org.drools.core.metadata.*;
import org.drools.beliefs.provenance.annotations.*;
import java.util.*;

global List list;

rule Init
when
then
    insertLogical( MyKlass_.newMyKlass( "123" ) );
    insertLogical( MyTargetKlass_.newMyTargetKlass( "000" ) );
    insertLogical( MyTargetKlass_.newMyTargetKlass( "001" ) );
end

rule Linkage
when
    $k : MyKlass()
    $t : MyTargetKlass( id == "000" )
    $q : MyTargetKlass( id == "001" )
then
    insertLogical( MyKlass_
                    .modify( $k, With.updates( $t, $q ) )
                    .links( Arrays.asList( $t, $q ), Lit.SET ) );
end

rule Linkage2
when
    $k : MyKlass( links!.size() == 2 )
    $t : MyTargetKlass( id == "000" )
then
    System.out.println( "Remove 000"  );
    insertLogical( MyKlass_
                    .modify( $k, With.updates( $t ) )
                    .links( $t, Lit.REMOVE ) );
    list.add( "000" );
end
