package org.drools.beliefs.provenance;

import org.test.*;
import com.foo.*;
import org.drools.core.metadata.*;
import org.drools.beliefs.provenance.annotations.*;
import static org.drools.core.metadata.With.with;
import java.util.*;
import static com.foo.MetaFactory.*;
import static org.test.MetaFactory.*;

global List list;

rule Init
when
then
    insertLogical( newMyKlass( "123" ) );
    insertLogical( newMyTargetKlass( "000" ) );
    insertLogical( newMyTargetKlass( "001" ) );
end

rule Linkage
when
    $k : MyKlass()
    $t : MyTargetKlass( id == "000" )
then
    System.out.println( "Found 000"  );
    insertLogical( modifyMyKlass( $k, with( $t ) )
                    .links( $t, Lit.ADD ) );
    list.add( "000" );
end

rule Linkage2
when
    $k : MyKlass( links!.size() == 1 )
    $t : MyTargetKlass( id == "001" )
then
    System.out.println( "Found 001"  );
    insertLogical( modifyMyKlass( $k, with( $t ) )
                    .links( $t, Lit.ADD ) );
    list.add( "001" );
end
