 *
 * Licensed under the Apache License, Version 2.0 (the "License");
/*
 * Copyright 2011 JBoss Inc
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.drools.chance.test;

import org.drools.chance.builder.Imperfect;
import org.drools.chance.builder.LinguisticPartition;

import de.lab4inf.fuzzy.FuzzySet;
import de.lab4inf.fuzzy.polygons.FuzzyTriangle;

global java.util.List list;


declare enum Weight
@LinguisticPartition


    /*

       SLIM      FAT
  1.0    | \     / |
         |   \ /   |
         |   / \   |
  0.0    | /     \ |
       --------------->
         0         100
    */

	SLIM( "slim", new de.lab4inf.fuzzy.polygons.FuzzyTriangle( -0.01, 0, 100 ) ),

	FAT( "fat", new de.lab4inf.fuzzy.polygons.FuzzyTriangle( 0, 100, 100.01 ) );

    label : String

    set   : FuzzySet

end


declare Imperson

	name    : String    = "john/0.3, philip/0.7"
	                @Imperfect( kind=ImpKind.PROBABILITY, type=ImpType.DISCRETE, degree=DegreeType.SIMPLE )

    body    : Weight
                    @Imperfect( kind=ImpKind.FUZZINESS, type=ImpType.LINGUISTIC, degree=DegreeType.SIMPLE, support="weight" )

    weight  : Double    = 65.0

end


rule "Init"
when
then
    insert( new Imperson( ) );
end


rule "Field vs Set"
when
    $b : Imperson( body is Weight.FAT )
then
    System.out.println( "X1 " + $b );
end


rule "Field vs Set II"
when
    $b : Imperson( body is Weight.SLIM )
then
    System.out.println( "X2 " + $b );
end