package org.drools.beliefs.provenance;

import org.test.*;
import com.foo.*;
import org.drools.core.metadata.*;
import org.drools.beliefs.provenance.annotations.*;
import java.util.*;
import static org.drools.core.metadata.With.with;

import static com.foo.MetaFactory.*;
import static org.test.MetaFactory.*;


global List list;

rule Init
when
then
    bolster( newMyKlass( "123" ) );
    bolster( newMyTargetKlass( "000" ) );
    bolster( newMyTargetKlass( "001" ) );
end

rule Linkage
when
    $k : MyKlass()
    $t : MyTargetKlass( id == "000" )
    $q : MyTargetKlass( id == "001" )
then
    bolster( modifyMyKlass( $k, with( $t, $q ) )
                    .links( Arrays.asList( $t, $q ), Lit.SET ) );
end

rule Linkage2
when
    $k : MyKlass( links!.size() == 2 )
    $t : MyTargetKlass( id == "000" )
    $q : MyTargetKlass( id == "001" )
then
    System.out.println( "Remove 000"  );
    bolster( modifyMyKlass( $k, with( $t, $q ) )
                    .links( Arrays.asList( $t, $q ), Lit.REMOVE ) );
    list.add( $k.getLinks().size() );
end
