package org.drools.beliefs.provenance;

import org.test.*;
import com.foo.*;
import static com.foo.MetaFactory.*;
import static org.test.MetaFactory.*;
import org.drools.core.metadata.*;
import org.drools.beliefs.provenance.annotations.*;
import static org.drools.core.metadata.With.with;
import java.util.*;

global List list;

rule Init
when
then
    bolster( newMyKlass( "123" ).prop( "hello" ) );
    bolster( newMyTargetKlass( "000" ) );
end


rule Log_1
when
    $t : MyTargetKlass( )
    $k : MyKlass( links contains $t )
then
    System.out.println( "Link 1 Success!" );
end

rule Log_2
when
    $k : MyKlass( )
    $t : MyTargetKlass( this memberOf $k.links )
then
    System.out.println( "Link 2 Success!" );
end

rule Linkage
when
    $k : MyKlass()
    $t : MyTargetKlass()
then
    bolster( modifyMyKlass( $k, with( $t ) )
                    .links( Arrays.asList( $t ), Lit.SET ) );
    list.add( $k.getId() );
    list.add( $k.getLinks().get( 0 ).getId() );
end
